### ISSUE TITLE
scala 2.10 branch for java 7

### ISSUE THREAD

**Issue by fommil** [scala/scala-swing#7]
java7 branch is tracking scala 2.11

**Comment by fommil** [comment]
@andy1138 what version of java is the 1.0.1 release aimed at?

If it's java6, any chance of a proper 2.10/2.11 release for java7?

**Comment by andy1138** [comment]
By 'aimed at' are you talking source code or binaries (as you know the
problem incompatibilities in the java source code not binaries )

Anything with version 1.x.x will be java6 source code ( 2.x.x  will be used
for java7 (and above) source code)

Both version have compiled targeting (ie -target:jvm-1.6 ). This AFAIK is
the same as the rest of the current scala distribution.

What is the advantage/reason  ?

**Comment by fommil** [comment]
I need source compat because we're compiling against scala-swing. Can you please release a 2.x.x for 2.10/2.11?

**Comment by fommil** [comment]
i.e. our java scala2.10 code won't compile if we compile against scala-swing compiled for java6.

**Comment by andy1138** [comment]
You only need to include

libraryDependencies +=  "org.scala-lang.modules" %% "scala-swing" % "1.0.1"

in your build.sbt to make it work with any scala 2.10/11 and with
java6/7/8. You dont need to recompile the scala-swing source code for every
project.

**Comment by fommil** [comment]
hmm, ok. Maybe things have changed, but this certainly didn't work in scala 2.9. I'll check and let you know.

**Comment by fommil** [comment]
you sure? http://search.maven.org/#search%7Cga%7C1%7Cscala-swing

**Comment by fommil** [comment]
the "org.scala-lang scala-swing 2.10.4" artifact definitely doesn't work with java 7.

**Comment by andy1138** [comment]
I also can't find scala-library for 2.10.4 in maven so do you know that
scala 2.10 is distributed that way?


I've just downloaded scala-2.10.4 and used java 1.7 to create a Frame. so I
would use the one included with the download, ie .zip/tgz (in the same way
as you are probably using scala-library )


Andys-MacBook-Pro:scala-2.10.4 andy$ scala
Welcome to Scala version 2.10.4 (Java HotSpot(TM) 64-Bit Server VM, Java
1.7.0_45).
Type in expressions to have them evaluated.
Type :help for more information.

scala> import scala.swing._
import scala.swing._

scala> import java.awt._
import java.awt._

scala> val f = new Frame("Hello")
f: java.awt.Frame =
java.awt.Frame[frame0,0,23,0x0,invalid,hidden,layout=java.awt.BorderLayout,title=Hello,resizable,normal]

scala> f.setVisible( true )

**Comment by fommil** [comment]
http://search.maven.org/#artifactdetails%7Corg.scala-lang%7Cscala-library%7C2.10.4%7Cjar

**Comment by andy1138** [comment]
so scala-swing-2.10.4 can be found at
http://search.maven.org/#artifactdetails%7Corg.scala-lang%7Cscala-swing%7C2.10.4%7Cjar

**Comment by fommil** [comment]
yes, I used that, and that's the one that causes the source compile problems above.

**Comment by fommil** [comment]
for this to work, the java7 branch of scala-swing needs to be compiled with java 7 (optionally with java6 class format, for **binary** compatibility, not source). Since we are actually using the Swing API and the Scala Swing API, everything needs to be right at the source level.

**Comment by fommil** [comment]
FYI, this works if we build locally as mentioned above.

**Comment by andy1138** [comment]
Hi

FYI, there is now a java7 build in mavin at
http://search.maven.org/#artifactdetails%7Corg.scala-lang.modules%7Cscala-swing_2.11%7C2.0.0-M1%7Cbundle

it's more to see of we can do a build but may also be something you're
interested in

Thanks
Andy

**Comment by fommil** [comment]
oh cool! Will try this out

**Comment by fommil** [comment]
@andy1138 and for scala 2.10?

**Comment by andy1138** [comment]
I'll see what I can do (now I'm getting better with the release process)

**Comment by fommil** [comment]
@andy1138 have a look at a few of my projects for travis and crossbuild ideas. Don't use SBT to manage the crossbuild, it's horrible. paulp's `sbt` script works like `sbt ++2.10.4 deploy` etc

**Comment by andy1138** [comment]
ok, thanks
deploy is also tied-up with some scripts from the main scala build so there
is limited scope for maneuver  but I'll play around with things and see
what happens.

**Comment by fommil** [comment]
@andy1138 any closer to a 2.10 binary?

Isn't it just a simple case of

```
sbt ++2.10.4 publish
```

??

**Comment by SethTisue** [comment]
fwiw, I wanted a version of 1.0.x that built on JDK 8, so I made one on a new `java8-2.11.x` branch. I ran a couple of the little demo programs with it and it seemed to work ok. I don't plan to publish an artifact from the branch.

**Comment by fommil** [comment]
oh I don't actually need this anymore. vote to close?

**Comment by andy1138** [comment]
Hi @SethTisue 
If your now creating JDK8 versions of the 1.0.x branch can you update the readme.md  on the https://github.com/scala/scala-swing  (the old plan was that 2.0.x was based on the change that you have now pulled into the 1.0x branch, I no longer know what the distinction is, or why you cant use the 2.0x version  )

**Comment by SethTisue** [comment]
@andy1138 This was purely in the context of Typesafe's Reactive Platform, which we're now building on JDK 8 instead of 6 like before. A core goal of the Reactive Platform is stability and using proven versions of things, so it would have felt odd to me to ship with a 2.0.x-labeled version of scala-swing given that there isn't an actual release in that series yet that isn't a milestone.

Also, I diffed the 1.0.x and 2.0.x trees and saw a lot of changes I'm not really in a position to evaluate (without sinking time into it, anyway), so sticking with 1.0.x but just flipping the 6 vs 8 switch seemed like the most conservative approach.

For a future version of RP, we'd consider including a 2.0.x release if by that time there is one that isn't a milestone.

I chose not to update the readme because I'm not really looking to give the branch I made any kind of "official" status outside the specific context of the Reactive Platform. If you're worried about users getting confused, another possible approach would be for us to relocate the branch to the typesafehub organization's fork of this repo. If you'd prefer that, let me know.

I have not followed scala-swing developments closely at all, so if any of the above seems misguided to you or based on incomplete or incorrect information, please let me know.  /cc @eed3si9n @adriaanm
